build:
  image: bjodah/bjodahimg20dev:v1.2.3
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - python2 -m pip install --upgrade wheel setuptools
    - python3 -m pip install --upgrade wheel setuptools
    - ./scripts/ci.sh pycodeexport
    - PATH=$HOME/.local/bin:$PATH ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: pycodeexport
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
