when:
  - event: [push]

steps:
  - name: build-and-test
    image: cont-reg.bjodah.se:443/bjodah/triceratops-3:17
    environment:
      - PYTHONMALLOC=malloc
    commands:
      - ./scripts/ci.sh ${CI_REPO_NAME}
      - ./scripts/prepare_deploy.sh
