{% set name = "pycodeexport" %}
{% set version = "0.1.1.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - sympy
    - mako
    - pycompilation
    - cython
    
test:
  requires:
    - pycompilation
  imports:
    - pycodeexport
    - pycodeexport.dist


about:
  home: https://github.com/bjodah/pycodeexport
  license: BSD 2-Clause
  summary: 'Python package for codegeneration.'
