package:
  name: pycodeexport
  #  version: "0.0.1"
  # the version is actually being set by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  path: ../

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  requires:
    - pycompilation


about:
  home: https://github.com/bjodah/pycodeexport
  license:  BSD License
  summary: 'Python package for codegeneration.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
