{% set name = "pycodeexport" %}
{% set version = "0.1.1.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - sympy
    - mako
    - pycompilation
    - cython
    
test:
  requires:
    - pycompilation
  imports:
    - pycodeexport
    - pycodeexport.dist


about:
  home: https://github.com/bjodah/pycodeexport
  license: BSD 2-Clause
  summary: 'Python package for codegeneration.'
