package:
  name: pycodeexport
  version: "0.0.5"

source:
  url: https://github.com/bjodah/pycodeexport/archive/master.zip

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  requires:
    - pycompilation

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/bjodah/pycodeexport
  license:  BSD License
  summary: 'Python package for codegeneration.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
